---
title: "processing data"
format: html
editor: source
---

## Set up

```{r libraries, message=FALSE, warning=FALSE}

library(tidyverse)
library(readr)
library(archive)
library(sysfonts)
```

## 1. Fetch


Read in data for stream temperature from Penn et al. 2023 data release

```{r fetch_temperature}
if(!file.exists("in/penn2023/nsegment_summary_seg_tave_water.csv")){
  print("Data not downloaded. Use script R_src/01_fetch_data.qmd before proceeding")
} else {
  segment_temp <- readr::read_csv("in/penn2023/nsegment_summary_seg_tave_water.csv", 
                        show_col_types = FALSE)
}

```


## 2. Process for Figure 3



```{r processing}
ave_temps <- segment_temp |> 
  pivot_longer(cols = !c(Date), names_to = "Segment", values_to = "Temperature") |>
  mutate(month = lubridate::month(Date)) |>
  group_by(Segment, month) |>
  summarize(mean_temp = mean(Temperature, na.rm = TRUE))

representative_segments <- ave_temps |> filter(Segment %in% c(51)) 

segment51 <- segment_temp |> rename(segment51 = "51") |> select(segment51, Date) |>
  mutate(year = lubridate::year(Date),
         yday = lubridate::yday(Date),
         month = lubridate::month(Date)) |>
  group_by(year, month) |>
  summarize(monthly_mean_temp = mean(segment51, na.rm = TRUE))

```

```{r page08}
font_main <- "Source Sans 3" 
sysfonts::font_add_google(font_main)

color_cold_optimal <- "#7EACB5"
color_cold_stress <- '#7A3608'#"#C96868"
color_warm_optimal <- "#7EACB5"
color_warm_stress <- '#7A3608'#"#C96868"

library(geomtextpath)
color_cold_optimal <- "#7EACB5"
color_cold_stress <- '#7A3608'#"#C96868"
color_warm_optimal <- "#7EACB5"
color_warm_stress <- '#7A3608'#"#C96868"


ggplot(data = representative_segments,  
       aes(y = mean_temp, x = month, color = Segment)) +
  # y-axis
  annotate(geom = "text", y = c(0, 10, 20, 30), x = rep(0.5, 4), 
           label = c(0, 10, 20, 30), 
           size = 16, color = "grey30", hjust = 1) +
  annotate(geom = "text", y = 30, x = 0.6, label = "degrees Celsius",
           size = 16, color = "grey30", hjust = 0) +
  annotate(geom = "line", y = rep(0,2), x = c(0.7,12), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = rep(10,2), x = c(0.7,9.2), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = rep(10,2), x = c(9.7,12), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = rep(20,2), x = c(0.7,9.7), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = rep(20,2), x = c(10.2,12), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = rep(30,2), x = c(3.7,12), linewidth = 0.8, color = "grey60") +
  # x-axis
  annotate(geom = "text", y = rep(-2, 12), x = 1:12, 
           label = c("J","F","M","A","M","J","J","A","S","O","N","D"), 
           size = 16, color = "grey30", hjust = 0.5) +
  annotate(geom = "line", y = c(-1,0.5), x = rep(1,2), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = c(-1,0.5), x = rep(2,2), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = c(-1,0.5), x = rep(3,2), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = c(-1,0.5), x = rep(4,2), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = c(-1,0.5), x = rep(5,2), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = c(-1,0.5), x = rep(6,2), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = c(-1,0.5), x = rep(7,2), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = c(-1,0.5), x = rep(8,2), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = c(-1,0.5), x = rep(9,2), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = c(-1,0.5), x = rep(10,2), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = c(-1,0.5), x = rep(11,2), linewidth = 0.8, color = "grey60") +
  annotate(geom = "line", y = c(-1,0.5), x = rep(12,2), linewidth = 0.8, color = "grey60") +
  # thermal stress thresholds
  annotate("line", x = c(1, 12), 
           y = c(24.1, 24.1), alpha = 0.7, 
           color = color_cold_stress, linewidth = 4) +  
  annotate("text", label = "Thermal stress threshold\nfor warm-adapted fish", 
           color = color_cold_stress,
           x = 0.5, y = 26.2, fontface = "bold",
           hjust = 0, size = 16, lineheight = 0.8) +
  # annual fluctuations
  geom_line(data = segment51,
            aes(y = monthly_mean_temp, x = month, group = year),
            linewidth = 1, color = "white", alpha = 0.5) +  
  geom_line(data = segment51,
            aes(y = monthly_mean_temp, x = month, group = year),
            linewidth = 0.5, color = color_warm_optimal) +  
  # Average across time 1979-2021
  geom_line(linewidth = 6.5, color = "white")  +
  geom_line(linewidth = 6, color = "#458869")  +
  # title
  annotate(geom = "text", y = 32, x = 0,          
           label = "Mean monthly stream temperature from 1979-2021",
           color = "black", hjust = 0, size = 18, vjust = 0, fontface = "bold") +
  # explainer label
  geom_textpath(label = "Annual values",
            size = 14, linewidth = 0, color = "#458869", 
            hjust = 0.87, vjust = 2.5) +
  geom_textpath(label = "1979-2021 average",
            size = 14, linewidth = 0, color = "#458869", 
            hjust = 0.81, vjust = -1.5, fontface = "bold", alpha = 1) +
  ylim(c(-2, 34)) +
  xlim(c(-0, 12)) +
  theme_void() +
  theme(panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white", color = NA))


# This png needs to be adjusted for web-sizes using the script "generate_responsive_images.sh"
#
ggsave(filename = "../public/assets/vectorized_pngs/page12.png", 
       width = 3000, height = 2300, dpi = 150, units = "px")

```




